In [8]:
import numpy as np

def metropolis_hastings_weight_calculation(a):
    """
    Calculates Metropolis-Hastings weights for a given adjacency matrix.

    Args:
      a: Adjacency matrix representing the initial relationships or connections.

    Returns:
      a_w: A new matrix with the same dimensions as 'a' containing the calculated Metropolis-Hastings weights.
    """
    a = np.array(a)
    num_nodes = len(a)
    a_w = np.zeros_like(a, dtype=float)

    degrees = np.sum(a, axis=1)
    max_degree = np.max(degrees)

    for i in range(num_nodes):
        for j in range(num_nodes):
            if i != j and a[i][j] != 0:  # Non-diagonal elements with an edge
                a_w[i][j] = 1 / (max(degrees[i], degrees[j]) + 1)
            elif i == j:  # Diagonal elements
                a_w[i][j] = 1 - sum(1 / (max(degrees[i], degrees[k]) + 1) for k in range(num_nodes) if a[i][k] != 0)

    return np.round(a_w, 2)

# Example usage
a = [
    [0, 1, 0, 0, 1],
    [1, 0, 1, 1, 0],
    [0, 1, 0, 1, 0],
    [0, 1, 1, 0, 1],
    [1, 0, 0, 1, 0]
]

a_w = metropolis_hastings_weight_calculation(a)
print(a_w)


[[0.42 0.25 0.   0.   0.33]
 [0.25 0.25 0.25 0.25 0.  ]
 [0.   0.25 0.5  0.25 0.  ]
 [0.   0.25 0.25 0.25 0.25]
 [0.33 0.   0.   0.25 0.42]]


In [9]:
import numpy as np

def metropolis_hastings_weight_calculation(a):
    """
    Calculates Metropolis-Hastings weights for a given adjacency matrix.

    Args:
      a: Adjacency matrix representing the initial relationships or connections.

    Returns:
      a_w: A new matrix with the same dimensions as 'a' containing the calculated Metropolis-Hastings weights.
    """
    a = np.array(a)
    num_nodes = len(a)
    a_w = np.zeros_like(a, dtype=float)

    degrees = np.sum(a, axis=1)
    max_degree = np.max(degrees)

    for i in range(num_nodes):
        for j in range(num_nodes):
            if i != j and a[i][j] != 0:  # Non-diagonal elements with an edge
                a_w[i][j] = 1 / (max(degrees[i], degrees[j]) + 1)
            elif i == j:  # Diagonal elements
                a_w[i][j] = 1 - sum(1 / (max(degrees[i], degrees[k]) + 1) for k in range(num_nodes) if a[i][k] != 0)

    return np.round(a_w, 2)

# Generating the adjacency matrix
a = [
    [0, 1, 0, 0, 1],
    [1, 0, 1, 1, 0],
    [0, 1, 0, 1, 0],
    [0, 1, 1, 0, 1],
    [1, 0, 0, 1, 0]
]

# Calculating the Metropolis-Hastings weights
a_w = metropolis_hastings_weight_calculation(a)

# Printing the resulting weight matrix
print(a_w)


[[0.42 0.25 0.   0.   0.33]
 [0.25 0.25 0.25 0.25 0.  ]
 [0.   0.25 0.5  0.25 0.  ]
 [0.   0.25 0.25 0.25 0.25]
 [0.33 0.   0.   0.25 0.42]]


In [13]:
import numpy as np

def generate_adjacency_matrix(size, density=0.5):
    """
    Generates a random adjacency matrix for an undirected graph.

    Args:
      size: The number of nodes in the graph.
      density: The probability of an edge existing between any two nodes.

    Returns:
      a: A random adjacency matrix.
    """
    a = np.random.rand(size, size) < density
    np.fill_diagonal(a, 0)  # No self-loops
    a = np.triu(a)  # Take the upper triangle
    a += a.T  # Mirror the upper triangle to the lower triangle to make it symmetric
    return a.astype(int)

def metropolis_hastings_weight_calculation(a):
    """
    Calculates Metropolis-Hastings weights for a given adjacency matrix.

    Args:
      a: Adjacency matrix representing the initial relationships or connections.

    Returns:
      a_w: A new matrix with the same dimensions as 'a' containing the calculated Metropolis-Hastings weights.
    """
    a = np.array(a)
    num_nodes = len(a)
    a_w = np.zeros_like(a, dtype=float)

    degrees = np.sum(a, axis=1)
    max_degree = np.max(degrees)

    for i in range(num_nodes):
        for j in range(num_nodes):
            if i != j and a[i][j] != 0:  # Non-diagonal elements with an edge
                a_w[i][j] = 1 / (max(degrees[i], degrees[j]) + 1)
            elif i == j:  # Diagonal elements
                a_w[i][j] = 1 - sum(1 / (max(degrees[i], degrees[k]) + 1) for k in range(num_nodes) if a[i][k] != 0)

    return np.round(a_w, 2)

# Generate a random adjacency matrix
size = 5  # Change the size as needed
adj_matrix = generate_adjacency_matrix(size, density=0.4)  # You can adjust the density as needed

# Calculating the Metropolis-Hastings weights
weights_matrix = metropolis_hastings_weight_calculation(adj_matrix)

# Printing the generated adjacency matrix and the resulting weight matrix
print("Adjacency Matrix:")
print(adj_matrix)
print("\nMetropolis-Hastings Weight Matrix:")
print(weights_matrix)

# Check if sum of each row and column equals 1
row_sums = np.sum(weights_matrix, axis=1)
col_sums = np.sum(weights_matrix, axis=0)

print("\nSum of each row:")
print(row_sums)
print("\nSum of each column:")
print(col_sums)


Adjacency Matrix:
[[0 1 0 1 1]
 [1 0 0 1 0]
 [0 0 0 1 0]
 [1 1 1 0 0]
 [1 0 0 0 0]]

Metropolis-Hastings Weight Matrix:
[[0.25 0.25 0.   0.25 0.25]
 [0.25 0.5  0.   0.25 0.  ]
 [0.   0.   0.75 0.25 0.  ]
 [0.25 0.25 0.25 0.25 0.  ]
 [0.25 0.   0.   0.   0.75]]

Sum of each row:
[1. 1. 1. 1. 1.]

Sum of each column:
[1. 1. 1. 1. 1.]
